---
driver:
  name: ec2
  aws_ssh_key_id: chef_ubuntu
  region: us-west-2
  availability_zone: c
  subnet_id: subnet-e492cfbc
  instance_type: t2.micro
  image_id: ami-0c2aba6c
  security_group_ids: sg-6eea6614
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: ~/.ssh/chef_ubuntu.pem

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[loadbalancer]

    verifier:
      inspec_tests:
        - test/smoke/default_test
    attributes:
